site_name: ""
site_description: 广东工业大学 生物信息学与脑科学课题组
site_url: https://mark7399.github.io/CJZ-labsite/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - content.code.copy
    - navigation.footer
    - navigation.top
  language: zh
  palette:
    - scheme: default
      primary: white
      accent: deep purple
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: 夜间模式

plugins:
  - bibtex:
      bib_file: docs/assets/refs.bib
  - i18n:
      docs_structure: suffix
      fallback_to_default: false
      reconfigure_material: true
      languages:
        - locale: zh
          default: true
          name: 中文
          nav:
            - HOME: index.zh.md
            - RESEARCH: research.zh.md
            - NEWS: news.zh.md
            - PUBLICATIONS:
              - 全部: publications.zh.md
              - 2024: publications/2024.zh.md
              - 2023: publications/2023.zh.md
              - 2022: publications/2022.zh.md
              - 2021: publications/2021.zh.md
              - 2020: publications/2020.zh.md
              - 2019-2016: publications/2019-2016.zh.md
            - MEMBERS: people.zh.md
            - JOIN US: contact.zh.md
            - GALLARY: gallary.zh.md
  - git-revision-date-localized:
      fallback_to_build_date: true

extra:
  social:
    - icon: material/school
      link: https://scholar.google.com/
    - icon: material/github
      link: https://github.com/

markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes
  - attr_list
  - tables
  - toc:
      permalink: true

extra_css:
  - assets/ux.css
  - assets/nav-top.css
  - assets/publications.css
extra_javascript:
  - assets/publications.js
  - assets/nav.js
